services:
  - type: web
    name: nexlink-api
    runtime: python
    buildCommand: "cd backend-django && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd backend-django && gunicorn nexlink.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nexlink-postgres-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"

  - type: web
    name: nexlink-signaling-server
    runtime: node
    buildCommand: "cd backend-node && npm install"
    startCommand: "cd backend-node && npm start"
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PORT
        value: 10000

  - type: web
    name: nexlink-frontend-app
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npx serve -s dist -l 10000"
    envVars:
      - key: NODE_VERSION
        value: 20.11.0

databases:
  - name: nexlink-postgres-db
    databaseName: nexlink_db
    user: nexlink_user
    plan: free